# Default values for mean-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
buildNumber: 1
image:
  repository: mandeepmehra/frontend
  tag: latest
  pullPolicy: Always
service:
  name: frontend-service
  type: NodePort
  nodePort: 30200
  externalPort: 80
  internalPort: 80
